server:
  port: 8080
  environment: dev
  prometheus_port: 9090

telegram:
  bot_token: ""

database:
  postgres_url: ""

logger:
  level: "info"

auth:
  jwt_secret: "CHANGE_ME"
  access_token_ttl_minutes: 15
  refresh_token_ttl_hours: 168